print("¡Hola, mundo!") #Est0 seria lo que se llama imprimir por pantalla en java pero en python pudiendo decir lo que queramos por pantalla
nombre = input("dime tu nombre:")
variable = input("dime tu numero favorito:")
print(nombre,"tu numero favorito es", variable, "te hare una escalera de este numero:")
print(1 * variable)
print(2 * variable)
print(3 * variable)
print(4 * variable)
print(5 * variable)
print(6 * variable)
print(7 * variable)
print(8 * variable)
print(9 * variable)
print(10 * variable)